#include <stddef.h>

size_t procprob(int a, short b, long *u, signed char *v) {
    *u += a;
    *v += b;
    return sizeof a + sizeof b;
}

/*
 * # size_t procprob(int a, short b, long *u, signed char *v)
 * # a in %edi, b in %si, u in %rdx, v in %rcx
 * procprob:
 *     movslq  %edi, %rdi      # sign-extend a
 *     addq    %rdi, (%rdx)    # *u += a
 *     addb    %sil, (%rcx)    # *v += b
 *     movl    $6, %eax        # sizeof a + sizeof b
 *     ret
 */

/*
 * I don't agree that there's another way to order the arguments in the
 * function prototype, because that changes the order in which arguments are
 * loaded into registers, invalidating the given assembly code. The assembly
 * generated by GCC appears to agree with me, but I'm not absolutely sure.
 */

size_t procprob2(short b, int a, signed char *v, long *u) {
    *u += a;
    *v += b;
    return sizeof a + sizeof b;
}
